# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Opening.destroy_all
puts "seeding openings..."


openings = [
  { name: "L'Italienne", pros: ["Jeu très naturel", "Bon contrôle du centre", "Développement rapide" ], cons: ["Le fou c4 peut se retrouver exposé", "Le centre noir n'est pas immédiatement mis sous pression"], suite_de_coups: "1. e4 e5, 2. Nf3 Nc6, 3. Bc4", color: "white", against: nil, video_url: "https://www.youtube.com/watch?v=5Ny8I1Bj-ek", image: "board_italienne.png", explications: [{image: "board_italian_e4", description: "Contrôle le centre et libère ton fou et ta dame."}, {image: "board_italian_Nf3", description: "Développe ton cavalier et attaque le pion e5."}, {image: "board_italian_Bc4", description: "Développe ton fou et vise f7, le point faible du camp noir"}], gendesc: "La partie italienne est l'une des plus anciennes ouvertures d'échecs. On la joue depuis le Moyen Âge ! Le classique 1.e4 peut mener à des parties lentes et positionnelles, comme à de furieuses batailles tactiques. Bien qu'elle soit très communément jouée par les débutants, la partie italienne fait également partie du répertoire des tous meilleurs joueurs du monde.\n\nLa partie italienne survient après les coups 1.e4 e5 2.Cf3 Cc6 3.Fc4. Les blancs développent leurs pièces de l'aile roi de manière très logique : le cavalier vient contrôler des cases centrales tandis que le fou attaque le point faible f7 et contrôle la case centrale d5.\n\nEn choisissant la partie italienne, les blancs respectent les principes de base de l'ouverture : développement des pièces, contrôle du centre et sécurité du roi. A partir de cette tabiya, la partie peut dériver vers un combat tactique ou positionnel.", logo: "knight_bleu" },
  { name: "L'Écossaise", pros: ["Les blancs se garantissent un avantage d'espace.", "Les noirs ne peuvent pas maintenir leur contrôle de la case e5.", "Evite les rouages ultra-théoriques de la partie espagnole." ], cons: ["Relâche la tension centrale.", "Joue deux fois le cavalier pour récupérer le pion d4.", "Le pion e4 peut devenir faible."], suite_de_coups: "1. e4 e5, 2. Nf3 Nc6, 3. d4", color: "white", against: nil, video_url: "https://www.youtube.com/watch?v=nWWe_byE3gM", image: "board_ecossaise.png", explications: [{image: "board_ecossaise_e4", description: "Contrôle le centre et libère ton fou et ta dame."}, {image: "board_ecossaise_Nf3", description: "Développe ton cavalier et attaque le pion e5."}, {image: "board_ecossaise_d4", description: "Attaque le centre et mets immédiatement la pression sur le pion e5."}], gendesc: "La partie écossaise est une très ancienne ouverture du pion e considérée comme l'une des meilleures alternatives à la partie espagnole. Excellente pour les débutants, c'est également une arme de choix pour viser la victoire à haut niveau.\n\nLa partie écossaise survient après les coups 1.e4 e5 2.Nf3 Nc6 3.d4. Les blancs frappent immédiatement au centre, forçant les noirs à abandonner leur pion central e5. Le coup d4 garantit donc un avantage d'espace aux blancs et permet d'éviter les longues lignes théoriques de la partie espagnole, ce qui est particulièrement pratique pour les débutants.\n\nEn revanche, ce troisième coup relâche la tension centrale un peu trop tôt. Les blancs vont également devoir investir un autre tempo pour récupérer le pion après la prise en d4.", logo: "knight_bleu" },
  { name: "Le Système de Londres", pros: ["Les noirs vont avoir du mal à obtenir du jeu", "Ils ne peuvent pas éviter la ligne", "Très bon moyen d'obtenir un milieu de jeu calme" ], cons: ["Peu d'opportunités d'attaque", "Ne met que très peu de pression sur la position noire", "Le fou f4 peut se retrouver exposé"], suite_de_coups: "1. d4 d5, 2. Nf3 Nf6, 3. Bf4", color: "white", against: nil, video_url: "https://www.youtube.com/watch?v=k86o1Wql56c", image: "board_systeme_londres", explications: [{image: "board_london_d4", description: "Contrôle le centre et libère ton fou."}, {image: "board_london_Nf3", description: "Développe ton cavalier et prépare ton roque."}, {image: "board_london_Bf4", description: "Sors ton fou avant de jouer e3 et place-le sur une case active."}], gendesc: "Le système de Londres est une ouverture du pion dame très populaire et à la réputation solide. On parle de système car quelque soit les réponses des noirs, les blancs vont plus ou moins toujours placer leurs pièces de la même manière. C'est pour cette raison que la théorie du système de Londres n'est pas aussi fournie que celles d'autres ouvertures.\n\nLes blancs entrent dans le système de Londres en jouant Ff4 avant de pousser leur pion en e3. Généralement, l'ordre de coups canonique est 1.d4 d5 2.Ff4. Notons tout de même qu'auparavant, la ligne principale était 1.d4 d5 2.Cf3 Cf6 3.Ff4, mais la théorie actuelle considère qu'il est légèrement plus précis de commencer par 2.Ff4 plutôt que 2.Cf3.\n\nL'idée principale de l'ouverture est de créer une solide structure de pions centrale en poussant c3 et e3, mais seulement après avoir développé le fou de cases noires hors de la chaîne de pions. Bien qu'il soit solide par nature, ce système comprend aussi quelques lignes agressives qui peuvent surprendre les noirs.", logo: "knight_bleu" },
  { name: "La Scandinave", pros: ["Les noirs ouvrent immédiatement le jeu", "Les deux fous noirs vont avoir du jeu", "Ouverture provocante" ], cons: ["Après la prise 2.exd5, les noirs perdent un temps pour reprendre", "Ce temps perdu créer le danger d'une attaque blanche rapide", "Les blancs ont généralement plus d'espace au centre"], suite_de_coups: "1. e4 d5", color: "black", against: "e4", video_url: "https://www.youtube.com/watch?v=1wHJGyWGVLA", image: "board_scandinave", explications: [{image: "board_scandinave", description: "Attaque immédiatement le pion e4 et conteste le centre."}], gendesc: "La défense scandinave est la septième défense la plus populaire pour les noirs face au coup 1.e4.\n\nLa défense scandinave est l'une des réponses les plus originales contre le coup 1.e4. Les noirs s'en prennent immédiatement au pion central par 1...d5.\n\nLa meilleure réponse blanche, et de très loin la plus populaire, consiste à s'emparer de ce pion par 2.exd5. Bien que ce soit le premier coup noir qui définit la défense scandinave, ce n'est que lorsque le pion est pris que commence l'ouverture proprement dite.", logo: "pawn_bleu" },
  { name: "La Française", pros: ["Solide, offre une structure saine", "Possibilités de contre-attaques éclairs", "Facile à apprendre" ], cons: ["Les noirs manquent d'espace", "Le fou de cases blanches est enfermée", "Peut mener à un jeu passif"], suite_de_coups: "1. e4 e6", color: "black", against: "e4", video_url: "https://www.youtube.com/watch?v=vVz6xqqtP1U", image: "board_francaise", explications: [{image: "board_francaise", description: "Prépare la poussée d5 pour contester le centre et libère ton fou de cases noires."}], gendesc: "La défense française est l'une des réponses noires les plus populaires contre le coup 1.e4. Elle figure au répertoire des maîtres depuis le XIXème siècle, et reste une des armes favorites des joueurs positionnels. Elle mène souvent à des parties assez lentes et constitue une option solide pour les joueurs de tous niveaux.\n\nLa défense française commence par les coups 1.e4 e6. Un coup qui prépare la poussée ...d5, qui va immédiatement s'en prendre au centre blanc. Le coup 1...e6 permet également d'ouvrir les diagonales pour le fou de cases noires et la dame, un avantage par rapport aux défenses Caro-Kann et slave.\n\nEn revanche, le coup 1...e6 emprisonne le fou de cases blanches des noirs, qui va avoir moins d'activité que dans une défense Caro-Kann ou une slave.\n\nLa défense française mène généralement à des parties lentes et fermées dans lesquelles les manœuvres de pièces et les ruptures de pions sont particulièrement importantes.", logo: "pawn_bleu" },
  { name: "La Caro-Kann", pros: ["Structure de pions saine", "Fou de cases blanches actif", "Rare, les blancs sont moins biens préparés" ,"Ouverture prudente et solide"], cons: ["Les noirs ont moins d'espace", "Développement lent", "Abondance de réponses blanches possibles"], suite_de_coups: "1. e4 c6", color: "black", against: "e4", video_url: "https://www.youtube.com/watch?v=hlL9WW5tAUw", image: "board_caro_kann", explications: [{image: "board_caro_kann", description: "Prépare la poussée d5 pour contester le centre tout en gardant ton fou libre."}], gendesc: "La défense Caro-Kann est avant tout connue pour sa solidité. Son coup fondateur, 1...c6, est le quatrième plus populaire contre 1.e4, avec une large avance sur le cinquième. Il prépare 2...d5 sans bloquer le fou de cases blanches, ce qui est considéré comme le principal défaut de sa cousine, la défense française. (1.e4 e6). Arme privilégiée des joueurs positionnels de tous niveaux.\n\nLa Caro-Kann commence par les coups 1.e4 c6, et continue la plupart du temps par 2.d4 d5. Les deux premiers coups peuvent être considérés comme le point de départ de la défense Caro-Kann.", logo: "pawn_bleu" },
  { name: "Le Gambit Dame refusé", pros: ["Très solide", "Bon contrôle du centre", "Rare, les blancs sont moins biens préparés", "Plans de jeu clairs"], cons: ["Le fou de cases blanches est enfermé", "Les noirs peuvent manquer d’espace", "Position parfois assez fermée"], suite_de_coups: "1. d4 d5, 2. c4 e6", color: "black", against: "d4", video_url: "https://www.youtube.com/watch?v=pE2cSSJdYRY", image: "board_gambit_dame_refuse", explications: [{image: "board_gambit_dame_refuse_d5", description: "Conteste le centre et empêche les Blancs de s'y installer seuls."}, {image: "board_gambit_dame_refuse_e6", description: "Renforce ton pion d5 et refuse de prendre le pion offert en c4."}], gendesc: "Le gambit dame est l'une des ouvertures du pion d les plus réputées pour les blancs. Contrairement aux ouvertures du pion 1.e4, il mène généralement à des parties stratégiques et non des batailles tactiques. Bien qu'elle soit jouée depuis des siècles, cette ouverture est toujours au répertoire de tout joueur d'élite qui se respecte. C'est également un excellent choix pour les joueurs débutants et intermédiaires.\n\nL’option choisie par les noirs est le gambit dame refusé. Les noirs ne prennent pas le pion c4 et préfèrent renforcer leur centre par 2...e6. Un choix solide, mais qui place en revanche un pion sur le chemin du fou de cases blanches.\n\nLes noirs vont ensuite généralement contre-attaquer le pion d4 à l'aide de la poussée c7-c5. La plupart du temps, l'un des deux camps accepte la création d'une faiblesse structurelle en échange de compensations dynamiques pouvant mener à l'initiative, voire à une attaque sur le roi.", logo: "pawn_bleu" },
  { name: "La Défense Slave", pros: ["La fou c8 a une bonne diagonale pour se développer.", "Les noirs maintiennent le contrôle du centre.", "Les noirs menacent parfois de s'emparer du pion c4." ], cons: ["Développement relativement lent.", "La rupture …c5 va prendre un coup de plus à réaliser.", "Le pion c6 bloque la case de développement naturelle du cavalier."], suite_de_coups: "1. d4 d5, 2. c4 c6", color: "black", against: "d4", video_url: "https://www.youtube.com/watch?v=_oHHm7MZAO8", image: "board_slave", explications: [{image: "board_slave_d5", description: "Conteste le centre avec ton propre pion."}, {image: "board_slave_c6", description: "Renforce ton pion d5 tout en gardant ton fou de cases blanches libre."}], gendesc: "La défense slave est une ouverture solide en réponse au gambit dame des blancs (1.d4 d5 2.c4). Les noirs se battent pour l'égalité contre l'une des ouvertures blanches les plus populaires, et ce sans se créer un mauvais fou de cases blanches (l'un des principaux inconvénients de la défense française et du gambit dame refusé).\n\nLa défense slave commence par les coups 1.d4 d5 2.c4 c6. Les noirs refusent de s'emparer du pion blanc en c4 et gardent un ferme contrôle du centre, en particulier de la case e4. Le caractéristique 2...c6 soutient le pion d5 sans enfermer le fou de cases blanches derrière la chaîne de pions, comme par exemple dans le gambit dame refusé ou la défense française.\n\nBien entendu, le coup 2...c6 a aussi ses inconvénients. Cette poussée ne développe aucune pièce, et le pion bloque désormais la case de développement la plus naturelle du cavalier.", logo: "pawn_bleu" },
  { name: "La Défense Hollandaise", pros: ["Originale", "Mène à des positions souples et déséquilibrées", "Rare, les blancs sont moins biens préparés" ], cons: ["Le coup …f5 affaiblit le roi noir", "Bien préparés, les blancs peuvent faire très mal", "Gain d'espace central facile pour l'adversaire"], suite_de_coups: "1. d4 f5", color: "black", against: "d4", video_url: "https://www.youtube.com/watch?v=nD6bXC6RQkM", image: "board_hollandaise", explications: [{image: "board_hollandaise", description: "Contrôle la case e4 et commence immédiatement à jouer de manière agressive sur l'aile roi."}], gendesc: "La défense hollandaise ressemble à une version \"miroir\" de la sicilienne (1.e4 c5). En effet, les deux ouvertures consistent à mobiliser en premier un pion de l'aile pour empêcher les blancs de construire un centre parfait. Mais en réalité, il existe une différence majeure : la poussée du pion f, qui gagne de l'espace mais affaiblit fortement la position du roi noir.\n\nPoint de depart :\n\nLa défense hollandaise commence généralement par les coups 1.d4 f5. Les noirs peuvent également commencer par 1...e6 avant de jouer 2...f5 pour éviter le gambit Staunton.", logo: "pawn_bleu" }
]

openings.each do |opening|
  Opening.create!(opening)
end
 puts "Seeded #{Opening.count} openings."
